#!/usr/bin/env node

var parser = require('xml2json');

process.stdin.resume();

var xml = ''
process.stdin.on('data', function(chunk) {
    xml += chunk;
});

process.stdin.on('end', function() {
    process.stdout.write(parser.toJson(xml));
});
